### ISSUE TITLE
You cannot use the DVD screen saver with this version of macOS.

### ISSUE THREAD

**Issue by esotericsean** [briantracy/DVDScreenSaver#2]
Something strange, been using (and loving) this screen saver daily. I haven't updated my OS or made any changes and just today it started giving me this error message when starting it.

I'm still on Mojave for some x86 app support.

**Comment by briantracy** [comment]
Interesting. I'll take a look at it. How did you install the `.saver` file? Did you build from source or use the zip I provided in the repo?

Also, how on earth did you find this program @esotericsean ? I don't think I publicized it anywhere, it's more of a hobby project!

**Comment by esotericsean** [comment]
You know something, this is embarrassing but I'm wondering if the one I have installed is from someone else. Been looking through my history but can't find it, pretty sure I found the one I have installed on Reddit. And when I Get Info on the .saver file I have installed it says Copyright 2020 Marty McLean 😅

Maybe yours works better. Let me see!

**Comment by esotericsean** [comment]
@briantracy Yep, yours works. Running from the compiled version in your .zip — sorry about the confusion! But also thanks for making this. I found it by searching for DVD screensaver on Google and just figured it was the one from the other guy, heh.

**Comment by briantracy** [comment]
@esotericsean It's funny that you bring that other one up, it's actually a direct theft of my project. If you compare the code, they are identical and his came out like a year later.

**Comment by esotericsean** [comment]
@briantracy Wow, I'm very glad I found yours, then. Awesome work! What a shame someone would steal like that.
